# Generated by Django 6.1.1 on 2026-09-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationRun',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_input', models.TextField()),
                ('state', models.CharField(choices=[('created', 'Created'), ('policy_checking', 'Policy Checking'), ('running', 'Running'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out'), ('failed', 'Failed')], default='created', max_length=30)),
                ('partial_output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='runtime.conversationrun')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('chunk_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('character_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runtime.conversationrun')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
